name = wiz
description = A 3 column layout with center symetry.
#preview = preview.png
template = wiz-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = highlighted
regions[content]        = Content
regions[main]           = main
;regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/wiz/wiz.layout.css
stylesheets[all][] = css/layouts/wiz/wiz.layout.no-query.css

