name = wizo
description = A 3 column layout with center symetry.
#preview = preview.png
template = wizo-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = highlighted
regions[content]        = Content
regions[main]           = main
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/wizo/wizo.layout.css
stylesheets[all][] = css/layouts/wizo/wizo.layout.no-query.css

